### ISSUE TITLE
error in tag

### ISSUE THREAD

**Issue by howlett** [Xilinx/u-boot-xlnx#29] opened 2015-06-29 17:51 UTC
Since git 2.1, there have been a number of new fsck options added which produce issues when I clone the repository.

$ git fsck --full
Checking object directories: 100% (256/256), done.
error in tag eb394f56db3e05d00891d6dc36a00df0025cf255: unterminated header
error in tag 9bf86baaa3b35b25baa2d664e2f7f6cafad689ee: unterminated header
error in tag c7071e6d645a8e13adb0d4cea2caad27213fa62f: unterminated header
Checking objects: 100% (319768/319768), done.
Checking connectivity: 319768, done.

These new tests are enabled by default when using git fsck.  I have been testing with git version 2.4.4.409.g5b1d901 and thought you might want to know so the error messages can be corrected.

**Comment by michalsimek** [comment] 2015-06-30 05:22
The problem is discussed here and needs to be fixed in the mainline first. http://lists.denx.de/pipermail/u-boot/2015-June/217138.html

**Closed** 2015-11-10 17:48 UTC
